# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/x/shef/shef_stage1_handoff_proof/shef_stage1_handoff_proof.srcs/sources_1/bd/zynq_mpsoc/ip/zynq_mpsoc_zynq_ultra_ps_e_0_0/zynq_mpsoc_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'zynq_mpsoc_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/x/shef/shef_stage1_handoff_proof/shef_stage1_handoff_proof.gen/sources_1/bd/zynq_mpsoc/ip/zynq_mpsoc_zynq_ultra_ps_e_0_0/zynq_mpsoc_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_mpsoc_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/x/shef/shef_stage1_handoff_proof/shef_stage1_handoff_proof.gen/sources_1/bd/zynq_mpsoc/ip/zynq_mpsoc_zynq_ultra_ps_e_0_0/zynq_mpsoc_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_mpsoc_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/x/shef/shef_stage1_handoff_proof/shef_stage1_handoff_proof.srcs/sources_1/bd/zynq_mpsoc/ip/zynq_mpsoc_zynq_ultra_ps_e_0_0/zynq_mpsoc_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'zynq_mpsoc_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/x/shef/shef_stage1_handoff_proof/shef_stage1_handoff_proof.gen/sources_1/bd/zynq_mpsoc/ip/zynq_mpsoc_zynq_ultra_ps_e_0_0/zynq_mpsoc_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_mpsoc_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/x/shef/shef_stage1_handoff_proof/shef_stage1_handoff_proof.gen/sources_1/bd/zynq_mpsoc/ip/zynq_mpsoc_zynq_ultra_ps_e_0_0/zynq_mpsoc_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_mpsoc_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
