# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_mpsoc/zynq_mpsoc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_mpsoc || ORIG_REF_NAME==zynq_mpsoc} -quiet] -quiet

# IP: bd/zynq_mpsoc/ip/zynq_mpsoc_zynq_ultra_ps_e_0_0/zynq_mpsoc_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_mpsoc_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zynq_mpsoc_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: e:/x/shef/shef_stage1_handoff_proof/shef_stage1_handoff_proof.gen/sources_1/bd/zynq_mpsoc/zynq_mpsoc_ooc.xdc
